### ISSUE TITLE
API won't run

### ISSUE THREAD

**Issue by Xoeseko** [sdgsolutionspace/sdg-market-api#3]
Despite many trials with and without docker I am unable to run the API locally meaning I cannot test anything. It would be nice if at least the documentation was updated with a full explanation of how to run the app locally because simply running the app with `ng serve` doesn't provide the API and the clasical `docker comopose` and `docker build` commands do not find what they need to map the API to where it is called.

**Comment by olivierb2** [comment]
Hi Xoeseko,

I guess we could try to build a proper and comprehensive documentation. In this waiting, you can have a look of this following docker compose.

```
version: '2'
services:
  cron:
    image: sdgsolspace/sdg-market-api
    environment:
      MYSQL_HOST: db
      MYSQL_DB: ghtrading
      MYSQL_USER: ghtrading
      MYSQL_PASSWORD: ghtrading
    stdin_open: true
    tty: true
    command:
    - app:git-parse-and-assign
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  sdg-market-api:
    image: sdgsolspace/sdg-market-api
    environment:
      MYSQL_HOST: db
      MYSQL_DB: ghtrading
      MYSQL_USER: ghtrading
      MYSQL_PASSWORD: ghtrading
      GITHUB_PARSER_LOGIN: sdgsolspace
      GITHUB_PARSER_PASSWORD: xxxxxx
      GITHUB_OAUTH_CLIENT_ID: xxxxxx
      GITHUB_OAUTH_CLIENT_SECRET: xxxxxx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  sdg-market-frontend:
    image: sdgsolspace/sdg-market-frontend
    environment:
      GITHUB_REDIRECT_URI: https://your-hosting-domain/callback
      BASE_URL: https://your-hosting-domain
      BASE_API_URL: https://your-hosting-domain/api/v1/
      GITHUB_CLIENT_ID: xxxxxxx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: ghtrading
      MYSQL_PASSWORD: ghtrading
      MYSQL_ROOT_PASSWORD: ghtrading
      MYSQL_USER: ghtrading
    stdin_open: true
    volumes:
    - /storage/docker/sdg/mysql:/var/lib/mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always

```
